version: '3.8'

services:
  easystreams:
    build: .
    container_name: easystreams
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=production
      - VERBOSE_LOGS=0
      - QUIET_PROVIDER_LOGS=1
      #- CF_PROXY_URL=https://********.workers.dev/
    restart: unless-stopped
    # Optional: Mount source code for development (uncomment if needed)
    # volumes:
    #   - ./src:/app/src
    #   - ./stremio_addon.js:/app/stremio_addon.js
